
import { PlaceHolderImages } from './placeholder-images';
import type { Dish } from './types';

const getImage = (id: string) => {
    const img = PlaceHolderImages.find(p => p.id === id);
    if (!img) {
        // Fallback to a default image if not found to prevent crashes
        const defaultImg = PlaceHolderImages.find(p => p.id === 'dish-1');
        if(!defaultImg) throw new Error(`Image with id ${id} and default image not found`);
        return defaultImg;
    }
    return img;
}

// This data is now for placeholder/fallback purposes only, as live data comes from Firestore.
export const dishes: Dish[] = [
  {
    id: '1',
    name: 'Margherita Bliss',
    description: 'Classic cheese and tomato sauce with fresh basil.',
    author: 'Jane Doe',
    userId: 'user-1',
    authorImage: getImage('author-1'),
    image: getImage('dish-8'),
    likes: 128,
    commentsCount: 23,
    category: 'Trending',
  },
  {
    id: '2',
    name: 'Pepperoni Paradise',
    description: 'Loaded with spicy pepperoni and melted mozzarella.',
    author: 'John Smith',
    userId: 'user-2',
    authorImage: getImage('author-2'),
    image: getImage('dish-1'), // using spaghetti for pepperoni
    likes: 256,
    commentsCount: 45,
    category: 'Popular',
  },
  {
    id: '3',
    name: 'Veggie Delight',
    description: 'A colorful mix of bell peppers, olives, onions, and mushrooms.',
    author: 'Emily White',
    userId: 'user-3',
    authorImage: getImage('author-3'),
    image: getImage('dish-10'),
    likes: 98,
    commentsCount: 18,
    category: 'Latest',
  },
  {
    id: '4',
    name: 'Classic Beef Royale',
    description: 'Juicy beef patty with lettuce, tomato, and cheese.',
    author: 'Michael Brown',
    userId: 'user-4',
    authorImage: getImage('author-4'),
    image: getImage('dish-3'),
    likes: 450,
    commentsCount: 88,
    category: 'Trending',
  },
  {
    id: '5',
    name: 'Spicy Chicken Crunch',
    description: 'Crispy chicken patty with a spicy mayo kick.',
    author: 'Jane Doe',
    userId: 'user-1',
    authorImage: getImage('author-1'),
    image: getImage('dish-2'),
    likes: 72,
    commentsCount: 12,
    category: 'Latest',
  },
  {
    id: '6',
    name: 'Artisanal Sushi Platter',
    description: 'A beautiful assortment of fresh nigiri and maki rolls. Made with high-quality fish.',
    author: 'John Smith',
    userId: 'user-2',
    authorImage: getImage('author-2'),
    image: getImage('dish-6'),
    likes: 310,
    commentsCount: 62,
    category: 'Popular',
  },
   {
    id: '7',
    name: 'Fluffy Pancakes with Berries',
    description: 'A stack of light and fluffy pancakes topped with fresh mixed berries and maple syrup.',
    author: 'Emily White',
    userId: 'user-3',
    authorImage: getImage('author-3'),
    image: getImage('dish-7'),
    likes: 180,
    commentsCount: 35,
    category: 'Trending',
  },
  {
    id: '8',
    name: 'Authentic Margherita Pizza',
    description: 'Classic Neapolitan pizza with San Marzano tomatoes, fresh mozzarella, and basil.',
    author: 'Michael Brown',
    userId: 'user-4',
    authorImage: getImage('author-4'),
    image: getImage('dish-8'),
    likes: 295,
    commentsCount: 55,
    category: 'Popular',
  },
  {
    id: '9',
    name: 'Hearty Ramen Noodle Soup',
    description: 'A comforting bowl of rich broth, tender noodles, and various toppings.',
    author: 'Jane Doe',
    userId: 'user-1',
    authorImage: getImage('author-1'),
    image: getImage('dish-9'),
    likes: 215,
    commentsCount: 40,
    category: 'Latest',
  },
  {
    id: '10',
    name: 'Fresh Garden Salad',
    description: 'A crisp and refreshing salad with a variety of greens, vegetables, and a light vinaigrette.',
    author: 'John Smith',
    userId: 'user-2',
    authorImage: getImage('author-2'),
    image: getImage('dish-10'),
    likes: 65,
    commentsCount: 10,
    category: 'Trending',
  },
  {
    id: '11',
    name: 'Street-Style Tacos al Pastor',
    description: 'Marinated pork tacos with pineapple, onions, and cilantro. A taste of Mexico City.',
    author: 'Emily White',
    userId: 'user-3',
    authorImage: getImage('author-3'),
    image: getImage('dish-11'),
    likes: 350,
    commentsCount: 70,
    category: 'Popular',
  },
  {
    id: '12',
    name: 'Morning Blueberry Muffins',
    description: 'Warm and moist blueberry muffins, perfect for breakfast or a snack.',
    author: 'Michael Brown',
    userId: 'user-4',
    authorImage: getImage('author-4'),
    image: getImage('dish-12'),
    likes: 150,
    commentsCount: 25,
    category: 'Latest',
  },
];
